version: "3.8"
services:
  react_app:
    build: .
    # working_dir: /app
    stdin_open: true
    # tty: true
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 